version: 0.0
os: linux
files:
– source: .
destination: /home/ec2-user/projet-annuel
hooks:
ApplicationStop:
  – location: scripts/application_stop.sh
  timeout: 300
  runas: ubuntu
ApplicationStart:
  – location: scripts/application_start.sh
  timeout: 300
  runas: ubuntu
