name: Deploy back-end aplication on EC2

on:
  push:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: Deploy Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ./
        target: "/home/${{ secrets.USERNAME }}"