# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy back-end aplication on AWS

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "src"
        target: "/home/${{ secrets.USERNAME }}"