# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy back-end aplication on AWS

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: eu-west-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://projet-annuel.s3-website.eu-west-3.amazonaws.com