# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy back-end aplication on AWS

on:
  push:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - name: Deploy Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "~/projet-annuel/*"
        target: "/home/${{ secrets.USERNAME }}"