name: Deploy back-end aplication on EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  deploy:
    needs: build
    env:
        ACCESS_TOKEN_SECRET: ${{ secrets.ENV_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN_EXPIRATION : ${{ secrets.ENV_ACCESS_TOKEN_EXPIRATION }}
        REFRESH_TOKEN_SECRET : ${{ secrets.ENV_REFRESH_TOKEN_SECRET }}
        REFRESH_TOKEN_EXPIRATION : ${{ secrets.ENV_REFRESH_TOKEN_EXPIRATION }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ./
        target: ${{ secrets.DIR_TARGET }}
    - name: start server nest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: npm start
