name: Build and Test Nestjs application

on: [push]

jobs:
  setup:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build application 
        run: npm run build

  test:     
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Test application 
        run: npm run test
      