name: Build And Test NestJs Application

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/starter.yml
  makeEnvironmentFile:
    runs-on: ubuntu-latest
    steps:
    - name: Make Environment File
      env:
          DB_HOST: ${{ secrets.ENV_DB_HOST }}
          DB_PORT: ${{ secrets.ENV_DB_PORT }}
          DB_USER: ${{ secrets.ENV_DB_USER }}
          DB_PASSWORD: ${{ secrets.ENV_DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.ENV_DB_DATABASE }}
      run: |
        touch .env
        echo DB_HOST=${{ secrets.ENV_DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.ENV_DB_PORT }} >> .env
        echo DB_USER=${{ secrets.ENV_DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }} >> .env
        echo DB_DATABASE=${{ secrets.ENV_DB_DATABASE }} >> .env