name: Build And Test NestJs Application

on:
  workflow_call:
  push:
    branches:
      [develop]
  pull_request:
    branches:
      [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        DB_HOST: ${{ secrets.ENV_DB_HOST }}
        DB_PORT: ${{ secrets.ENV_DB_PORT }}
        DB_USER: ${{ secrets.ENV_DB_USER }}
        DB_PASSWORD: ${{ secrets.ENV_DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.ENV_DB_DATABASE }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ENV_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN_EXPIRATION: ${{ secrets.ENV_ACCESS_TOKEN_EXPIRATION }}
        REFRESH_TOKEN_SECRET: ${{ secrets.ENV_REFRESH_TOKEN_SECRET }}
        REFRESH_TOKEN_EXPIRATION: ${{ secrets.ENV_REFRESH_TOKEN_EXPIRATION }}
        directory: ${{ secrets.DIR_TARGET }}
        file_name: .env
        fail_on_empty: false
